// Generates src/components/ui/icons.tsx from the official Feather icon set (MIT).
// Usage: node scripts/generate-icons.mjs
import { readFileSync, writeFileSync } from "node:fs";
import { createRequire } from "node:module";

const require = createRequire(import.meta.url);
const icons = JSON.parse(readFileSync(require.resolve("feather-icons/dist/icons.json"), "utf8"));

const names = [
  "alert-circle", "alert-triangle", "arrow-down-left", "arrow-up-right", "check", "check-circle",
  "chevron-down", "chevron-left", "chevron-right", "clock", "credit-card", "download", "edit-2",
  "home", "inbox", "info", "key", "list", "loader", "lock", "log-out", "mail", "minus", "pie-chart",
  "plus", "refresh-cw", "settings", "target", "trash-2", "user", "wifi", "wifi-off", "x"
];

const toPascal = (name) => name.split("-").map((part) => part[0].toUpperCase() + part.slice(1)).join("");
const toJsx = (svg) => svg
  .replace(/stroke-(\w+)=/g, (_, rest) => `stroke${rest[0].toUpperCase()}${rest.slice(1)}=`)
  .replace(/fill-rule=/g, "fillRule=").replace(/clip-rule=/g, "clipRule=");

const body = names.map((name) => {
  if (!icons[name]) throw new Error(`Unknown Feather icon: ${name}`);
  return `export const Icon${toPascal(name)} = createIcon("${name}", <>${toJsx(icons[name])}</>);`;
}).join("\n");

writeFileSync(new URL("../src/components/ui/icons.tsx", import.meta.url), `// Generated by scripts/generate-icons.mjs from feather-icons (MIT). Do not edit by hand.
import { forwardRef } from "react";
import type { ReactNode, SVGProps } from "react";
import { cn } from "@/lib/utils";

export type IconProps = SVGProps<SVGSVGElement> & { size?: number | string };

function createIcon(name: string, children: ReactNode) {
  const Icon = forwardRef<SVGSVGElement, IconProps>(({ size = 24, className, strokeWidth = 2, ...props }, ref) => (
    <svg ref={ref} xmlns="http://www.w3.org/2000/svg" width={size} height={size} viewBox="0 0 24 24" fill="none"
      stroke="currentColor" strokeWidth={strokeWidth} strokeLinecap="round" strokeLinejoin="round"
      aria-hidden="true" data-icon={name} className={cn("shrink-0", className)} {...props}>{children}</svg>
  ));
  Icon.displayName = \`Icon(\${name})\`;
  return Icon;
}

${body}
`);
console.log(`Generated ${names.length} icons.`);
